name: Cachix

on:
  push:
    branches: [ main ]

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Cachix
        uses: cachix/cachix-action@v12
        with:
          name: accentor
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: nix build -L --no-link .#devShells.$(nix eval --impure --expr "builtins.currentSystem").accentor-android
      - run: nix eval --json ".#devShells.$(nix eval --impure --expr 'builtins.currentSystem').accentor-android.outPath" | sed 's/"\(.*\)"/\1/' | cachix push accentor
