name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/cache@v6.1.0
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/setup-java@v6.0.0
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v4.0.1
    - name: Build release APK
      run: |
        ./gradlew assembleRelease
        $ANDROID_SDK_ROOT/build-tools/34.0.0/zipalign -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-unsigned-aligned.apk
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > keystore.jks
        echo "${{ secrets.KEYSTORE_PASSWORD }}" | $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner sign --ks keystore.jks --out "accentor-$GITHUB_REF_NAME.apk" app/build/outputs/apk/release/app-release-unsigned-aligned.apk
        $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner verify accentor-$GITHUB_REF_NAME.apk
    - name: Create release
      run: gh release create "$GITHUB_REF_NAME" "accentor-$GITHUB_REF_NAME.apk" --generate-notes --verify-tag
      env:
        GH_TOKEN: ${{ github.token }}
