name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/cache@v2.1.6
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v2.0.7
    - name: Build release APK
      run: |
        ./gradlew assembleRelease
        $ANDROID_SDK_ROOT/build-tools/30.0.2/zipalign -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-unsigned-aligned.apk
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > keystore.jks
        echo "${{ secrets.KEYSTORE_PASSWORD }}" | $ANDROID_SDK_ROOT/build-tools/30.0.2/apksigner sign --ks keystore.jks --out app-release.apk app/build/outputs/apk/release/app-release-unsigned-aligned.apk
        $ANDROID_SDK_ROOT/build-tools/30.0.2/apksigner verify app-release.apk
        mv app-release.apk accentor-$(git describe --tags).apk
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: "accentor-*.apk"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
