name: Update

on:
  schedule:
    - cron: '30 */2 * * *'
  workflow_dispatch:

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Cachix
        uses: cachix/cachix-action@v14
        with:
          name: accentor
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: nix flake update
      - run: nix build -L --no-link .#devShells.$(nix eval --impure --expr "builtins.currentSystem").accentor-android
      - run: nix eval --json ".#devShells.$(nix eval --impure --expr 'builtins.currentSystem').accentor-android.outPath" | sed 's/"\(.*\)"/\1/' | cachix push accentor
      - uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: "Update flake dependencies"
